# Axolotl LoRA训练配置 - SSAP框架数据集
# 使用方法: axolotl train axolotl_config.yaml

base_model: meta-llama/Llama-2-7b-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: true
load_in_4bit: false
strict: false

# LoRA设置
adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
lora_target_linear: true
lora_fan_in_fan_out:

# 数据集配置
datasets:
  - path: SSAP_LoRA_Dataset.json
    type: alpaca
    train_on_inputs: false
    group_by_length: true

# 训练配置
dataset_prepared_path: ./prepared_ssap_dataset
val_set_size: 0.2
output_dir: ./ssap_lora_out

# 序列配置
sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

# 训练参数
micro_batch_size: 2
gradient_accumulation_steps: 4
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: linear
learning_rate: 0.0002

# 训练设置
train_on_inputs: false
group_by_length: false
bf16: auto
fp16: 
tf32: false

# 梯度检查点和保存
gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:

# 日志和评估
logging_steps: 10
eval_steps: 50
save_steps: 100
save_total_limit: 3

# Wandb日志（可选）
wandb_project: ssap-lora-training
wandb_entity:
wandb_watch:
wandb_name: ssap-framework-lora
wandb_log_model:

# 特殊设置
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

# SSAP框架特定验证
validation_split: 0.2
eval_table_size:
eval_table_max_new_tokens: 128

# 推理设置
inference:
  max_new_tokens: 512
  do_sample: true
  temperature: 0.7
  top_p: 0.9
  repetition_penalty: 1.1

# SSAP框架质量检查
ssap_evaluation:
  check_architecture_format: true
  check_workflow_syntax: true
  check_format_modules: true
  check_calling_convention: true
  
  # 预期质量指标
  target_metrics:
    architecture_consistency: 0.90
    calling_standardization: 0.95
    logic_clarity: 0.85
    professional_accuracy: 0.90 